from pymongo import MongoClient
# Replace with your MongoDB Atlas connection string
client = MongoClient('mongodb://localhost:27017/?retryWrites=true&w=majority')
db = client['main']
# Add a new collection for currencies
currency_collection = db['currency']

# Seed the currency collection with some common currencies if it's empty
if currency_collection.count_documents({}) == 0:
    currencies = [
    {"code": "USD", "name": "US Dollar"},
    {"code": "EUR", "name": "Euro"},
    {"code": "GBP", "name": "British Pound"},
    {"code": "AUD", "name": "Australian Dollar"},
    {"code": "CAD", "name": "Canadian Dollar"},
    {"code": "CHF", "name": "Swiss Franc"},
    {"code": "CNY", "name": "Chinese Yuan"},
    {"code": "JPY", "name": "Japanese Yen"},
    {"code": "ZAR", "name": "South African Rand"},
    {"code": "INR", "name": "Indian Rupee"},
    {"code": "BRL", "name": "Brazilian Real"},
    {"code": "RUB", "name": "Russian Ruble"},
    {"code": "MXN", "name": "Mexican Peso"},
    {"code": "SGD", "name": "Singapore Dollar"},
    {"code": "HKD", "name": "Hong Kong Dollar"},
    {"code": "KRW", "name": "South Korean Won"},
    {"code": "TRY", "name": "Turkish Lira"},
    {"code": "SEK", "name": "Swedish Krona"},
    {"code": "NOK", "name": "Norwegian Krone"},
    {"code": "DKK", "name": "Danish Krone"},
    {"code": "NZD", "name": "New Zealand Dollar"},
    {"code": "PLN", "name": "Polish Zloty"},
    {"code": "THB", "name": "Thai Baht"},
    {"code": "IDR", "name": "Indonesian Rupiah"},
    {"code": "MYR", "name": "Malaysian Ringgit"},
    {"code": "PHP", "name": "Philippine Peso"},
    {"code": "AED", "name": "United Arab Emirates Dirham"},
    {"code": "SAR", "name": "Saudi Riyal"},
    {"code": "QAR", "name": "Qatari Riyal"},
    {"code": "ILS", "name": "Israeli New Shekel"},
    {"code": "CLP", "name": "Chilean Peso"},
    {"code": "ARS", "name": "Argentine Peso"},
    {"code": "EGP", "name": "Egyptian Pound"},
    {"code": "VND", "name": "Vietnamese Dong"},
    {"code": "PKR", "name": "Pakistani Rupee"},
    {"code": "COP", "name": "Colombian Peso"},
    {"code": "CZK", "name": "Czech Koruna"},
    {"code": "HUF", "name": "Hungarian Forint"},
    {"code": "RON", "name": "Romanian Leu"},
    {"code": "BGN", "name": "Bulgarian Lev"},
    {"code": "NGN", "name": "Nigerian Naira"},
    {"code": "KES", "name": "Kenyan Shilling"},
    {"code": "GHS", "name": "Ghanaian Cedi"},
    {"code": "UGX", "name": "Ugandan Shilling"},
    {"code": "TZS", "name": "Tanzanian Shilling"},
    {"code": "ETB", "name": "Ethiopian Birr"},
    {"code": "DZD", "name": "Algerian Dinar"},
    {"code": "MAD", "name": "Moroccan Dirham"},
    {"code": "XOF", "name": "West African CFA Franc"},
    {"code": "XAF", "name": "Central African CFA Franc"},
    {"code": "KWD", "name": "Kuwaiti Dinar"},
    {"code": "OMR", "name": "Omani Rial"},
    {"code": "BHD", "name": "Bahraini Dinar"},
    {"code": "JOD", "name": "Jordanian Dinar"},
    {"code": "LBP", "name": "Lebanese Pound"},
    {"code": "LKR", "name": "Sri Lankan Rupee"},
    {"code": "BDT", "name": "Bangladeshi Taka"},
    {"code": "NPR", "name": "Nepalese Rupee"},
    {"code": "MMK", "name": "Myanmar Kyat"},
    {"code": "KZT", "name": "Kazakhstani Tenge"},
    {"code": "AZN", "name": "Azerbaijani Manat"},
    {"code": "UZS", "name": "Uzbekistani Som"},
    {"code": "GEL", "name": "Georgian Lari"},
    {"code": "AFN", "name": "Afghan Afghani"},
    {"code": "TMT", "name": "Turkmenistani Manat"},
    {"code": "BND", "name": "Brunei Dollar"},
    {"code": "BWP", "name": "Botswana Pula"},
    {"code": "ZMW", "name": "Zambian Kwacha"},
    {"code": "MWK", "name": "Malawian Kwacha"},
    {"code": "RSD", "name": "Serbian Dinar"},
    {"code": "ALL", "name": "Albanian Lek"},
    {"code": "ISK", "name": "Icelandic Krona"},
    {"code": "MKD", "name": "Macedonian Denar"},
    {"code": "MNT", "name": "Mongolian Tugrik"},
    {"code": "BAM", "name": "Bosnia and Herzegovina Convertible Mark"},
    {"code": "MOP", "name": "Macanese Pataca"},
    {"code": "PEN", "name": "Peruvian Sol"},
    {"code": "UYU", "name": "Uruguayan Peso"},
    {"code": "PYG", "name": "Paraguayan Guarani"},
    {"code": "GTQ", "name": "Guatemalan Quetzal"},
    {"code": "CRC", "name": "Costa Rican Colón"},
    {"code": "BOB", "name": "Bolivian Boliviano"},
    {"code": "DOP", "name": "Dominican Peso"},
    {"code": "HNL", "name": "Honduran Lempira"},
    {"code": "SVC", "name": "Salvadoran Colón"},
    {"code": "NIO", "name": "Nicaraguan Córdoba"},
    {"code": "BBD", "name": "Barbadian Dollar"},
    {"code": "BZD", "name": "Belize Dollar"},
    {"code": "XCD", "name": "East Caribbean Dollar"},
    {"code": "JMD", "name": "Jamaican Dollar"},
    {"code": "TTD", "name": "Trinidad and Tobago Dollar"},
    {"code": "FJD", "name": "Fijian Dollar"},
    {"code": "PGK", "name": "Papua New Guinean Kina"},
    {"code": "SBD", "name": "Solomon Islands Dollar"},
    {"code": "VUV", "name": "Vanuatu Vatu"},
    {"code": "MVR", "name": "Maldivian Rufiyaa"},
    {"code": "SCR", "name": "Seychellois Rupee"},
    {"code": "MGA", "name": "Malagasy Ariary"},
    {"code": "SRD", "name": "Surinamese Dollar"},
]

    currency_collection.insert_many(currencies)